package com.siva.restlearning.SivasFolderMVC.DBConnection.service;

import java.util.HashMap;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.lang.NonNull;
import org.springframework.stereotype.Service;

import com.siva.restlearning.SivasFolderMVC.DBConnection.model.Mobile;
import com.siva.restlearning.SivasFolderMVC.DBConnection.repository.MobileRepository;

@Service
public class MobileService {

    @Autowired
    MobileRepository mobileRepository;


    public List<Mobile> getAllMobiles() {
        return mobileRepository.getAllData();
    }


    public HashMap<String, Object> addMobile(@NonNull Mobile mobile) {
        mobileRepository.save(mobile);
        HashMap<String, Object> response = new HashMap<>();
        response.put("message", "Mobile added successfully");
        response.put("mobile", mobile);
        return response;
    }


    public List<Mobile> getMobilesByBrand(String brand) {
        return mobileRepository.findByBrand(brand);
    }


    public String addMobileByQuery(Mobile mobile) {

        // The Getter Methods For The Mobile's Properties Are Generated By Lombok's @Data Annotation In The Mobile Entity Class
        
        return mobileRepository.addMobileByQuery(mobile.getBrand(), mobile.getModel(), mobile.getPrice());
    }


    public ResponseEntity<?> updateMobile(@NonNull Long id, Mobile mobile) {
        return mobileRepository.findById(id).map(existingMobile -> { 
            // Above Line Is for Finding The Item Based On Id, If Found Then Update It, If Not Found Then Return 404 Response


            // Using Setters To Update The Existing Mobile's Properties With The New Values From The Request Body  These Setters Are Generated By Lombok's @Data Annotation In The Mobile Entity Class
            existingMobile.setBrand(mobile.getBrand());
            existingMobile.setModel(mobile.getModel());
            existingMobile.setPrice(mobile.getPrice());

            // Saving The Updated Mobile Back To The Database
            mobileRepository.save(existingMobile);

            // Returning A Success Response With The Updated Mobile Information
            return ResponseEntity.ok("Mobile updated successfully");
        }).orElseGet(() -> ResponseEntity.status(404).body("Mobile not found with id: " + id));
    }


    public ResponseEntity<?> deleteMobile(Long id) {
        // Finding The Mobile By Id, If Found Then Delete It, If Not Found Then Return 404 Response
        return mobileRepository.findById(id).map(mobile -> {
            // The above line is for finding the item based on id, if found then delete it, if not found then return 404 response
            mobileRepository.delete(mobile);
            // The Above Line Deletes The Found Mobile From The Database
            return ResponseEntity.ok("Mobile deleted successfully");
            // Returning A Success Response After Deletion
        }).orElseGet(() -> ResponseEntity.status(404).body("Mobile not found with id: " + id)); 
    }

}
